config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :chairs
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get 'admin/dashboard'

  get 'chart', to: 'admin#show_chart'

  root "static_pages#home"

  #resources users
  resources :users,  only: [:index, :edit, :update]

  resources :billings, only: [:new, :create, :index, :show, :delete]

  namespace :admin do
    resources :users
    resources :chairs
    resources :categories
    resources :billings, only: [:index, :show]
  end
  
  #rating
  post 'rating', to: 'chairs#rating'
  get 'rating', to: 'chairs#get_rating'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]
  
  # before_save :downcase_email
  
  enum role: [:user, :admin]
  
  # VALID_DATE_REGEX = /[0-3]{1}[0-9]{1}\/[0-1]{1}[0-9]{1}\/[1-2]{1}[0-9]{3}/
  # VALID_DATE_REGEX = /[1-2]{1}[0-9]{3}\/[0-1]{1}[0-9]{1}\/[0-3]{1}[0-9]{1}/
  # validates :birthday, format: { with: VALID_DATE_REGEX}
  validates :gender, inclusion: {in: ["male", "female"]}, allow_nil: true
  validates :role, inclusion: {in: ["user", "admin"]}

  # validates :nickname,  presence: true, length: {maximum: 30}
  
  after_initialize :set_default_role, :if => :new_record?
  #recommend_history
  has_many :recommend_histories
  
  mount_uploader :img, ImageUploader
  def set_default_role
    self.role ||= :user
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        name: data['name'],
        email: data['email'],
        password: Devise.friendly_token[0,20],
        role: :user,
        nickname: data['name'],
        remote_img_url: data['image']
      )
    end
    user
end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :verify_is_admin
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  
  layout 'admin'
  def index
    @users = User.all.page(params[:page]).per(10)
  end
  
  def show
    flash[:success] = ""
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Successfully!!!"
      render :new
    else
      flash[:danger] = "Not successful"
      redirect_to :back
    end
  end
    
  def edit
  end
  
  def update
    # @user = find_user
    if @user.update_attributes user_params
      flash[:success] = "Profile update"
      redirect_to :back
    else
      render :edit
    end
  end
  
  def destroy
    if @user.destroy
      flash[:success] = t("user_deleted")
    else
      flash[:danger] = t("cannot_delete")
    end
    redirect_to :back
  end
  
  private

  def verify_is_admin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
  
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :birthday, :gender
  end
  
  def find_user
    @user = User.find_by id: params[:id]

    return @user if @user
    flash[:warning] = t("no_user_warning")
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
    
    def edit
        @user = current_user
    end
    def update
        # @product = User.find(params[current_user.id])
        @user = current_user
        if @user.update_attributes(user_params)
          flash[:success] = "User updated"
          redirect_to users_path
        else   
          flash[:error] = 'Failed to edit user!'   
          render :edit   
        end   
    end
    
    def user_params   
        params.require(:user).permit(:name, :gender, :birthday, :nickname, :img)
    end   
end

app/views/admin/users/edit.html.erb
<div class="content-wrapper">
    <section class="content-header">
        <h1>
          Edit 
        </h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
          <li class="active">User</li>
          <li class="active">Edit</li>
        </ol>
    </section>
    <br>
    <section class="content" style="height:1000px">
        <% if @user.errors.full_messages.any? %>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <% @user.errors.full_messages.each do |error_message| %>
                  <strong><%= error_message if @user.errors.full_messages.first == error_message %></strong> <br />
                <% end %>
        </div>
        <% end %>
        <% flash.each do |key, value| %>
            <div id="error_explanation">
              <div class="alert alert-#{key}">
                <%= value unless value.blank? %>
              </div>
            </div>
        <% end %>
        <%= form_for(@user, as: :user, :html => {:class => 'row'}, url: admin_user_path(@user.id), method: :put) do |f| %>
            <div class="col-md-12 form-group p_star">
                <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Name", value: @user.name %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email", value: @user.email, :disabled => true%>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.password_field :password, autocomplete: "new-password", class: "form-control", placeholder: "Password" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", placeholder: "Password Confirmation" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.date_field :birthday, autofocus: true, autocomplete: "birthday", class: "form-control", placeholder: "Birthday", value: f.object.try(:strftime, @user.birthday) %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.select(:gender, ['male', 'female'], {:selected => @user.gender}, { :class => 'form-control'}) %>
            </div>
            <div class="col-md-12 form-group">
                <%= f.submit "Edit", class: "btn btn-primary" %>
            </div>
        <% end %>
    </section>
</div>

app/views/admin/users/index.html.erb
<div class="content-wrapper">
    <section class="content-header">
    <h1>
      User List
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">User</li>
      <li class="active">List</li>
    </ol>
    </section>
    <br>
    <section class="content" style="height:1000px">
        <%= link_to "New", new_admin_user_path, {:class=>'btn btn-primary'}%>
        <table class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Image</th>
              <th scope="col">Role</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
              <%- @users.each do |user| %>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= image_tag current_user.img? ? user.img.url : "http://file.vforum.vn/hinh/2018/02/hinh-cho-cuoi-deu-cho-de-thuong-12.jpg", width: '100' %></td>
                  <td><%= user.role.upcase %></td>
                  <td><%= link_to "Edit", edit_admin_user_path(user.id), {:class=>'btn btn-warning'}%>
                      <%= link_to "Delete", admin_user_path(user.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
        <%= paginate @users, theme: 'twitter-bootstrap-3' %>
        
    </section>
</div>

app/views/admin/users/new.html.erb
<div class="content-wrapper">
    <section class="content-header">
        <h1>
          New
        </h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
          <li class="active">User</li>
          <li class="active">New</li>
        </ol>
    </section>
    <br>
    <section class="content"style="height:1000px">
        <% if @user.errors.full_messages.any? %>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <% @user.errors.full_messages.each do |error_message| %>
                  <strong><%= error_message if @user.errors.full_messages.first == error_message %></strong> <br />
                <% end %>
        </div>
        <% end %>
        <% flash.each do |key, value| %>
            <div id="error_explanation">
              <div class="alert alert-#{key}">
                <%= value unless value.blank? %>
              </div>
            </div>
        <% end %>
        <%= form_for(User.new, as: :user, :html => {:class => 'row'}, url: admin_users_path, method: :post) do |f| %>
            <div class="col-md-12 form-group p_star">
                <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Name" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.password_field :password, autocomplete: "new-password", class: "form-control", placeholder: "Password" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", placeholder: "Password Confirmation" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.date_field :birthday, autofocus: true, autocomplete: "birthday", class: "form-control", placeholder: "Birthday" %>
            </div>
            <div class="col-md-12 form-group p_star">
                <%= f.select(:gender, ['male', 'female'], {}, { :class => 'form-control' }) %>
            </div>
            <div class="col-md-12 form-group">
                <%= f.submit "Create", class: "btn btn-primary" %>
            </div>
        <% end %>
    </section>
</div>